spring-profile-service:
  property1-dev: value11
  property2-dev: value12
  
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/sample2?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver