spring-vehicle-service:
  property1-qual: value21
  property2-qual: value22
  
spring:
   datasource:
    url: jdbc:mysql://localhost:3306/sample2?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver